# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow will install Deno then run Deno lint and test.
# For more information see: https://github.com/denoland/setup-deno

name: Deno

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      # Uncomment this step to verify the use of 'deno fmt' on each commit.
      # - name: Verify formatting
      #   run: deno fmt --check

      # - name: Run linter
      #   run: deno lint

      - name: Run tests
        run: DEV_MODE=test deno test -A --unstable

      - name: Check lib/bgl
        run: XDG_CACHE_HOME=$(pwd) compiler/run.sh check lib/bgl

      - name: Test lib/bgl
        run: XDG_CACHE_HOME=$(pwd) compiler/run.sh test lib/bgl

      - name: Check tests/bagel-cms/index.bgl
        run: XDG_CACHE_HOME=$(pwd) compiler/run.sh check tests/bagel-cms/index.bgl

